name: Create the Release pull request

on:
  workflow_dispatch:
  # testing
  push:
    branches:
      - feature/create-release-pr-workflow

jobs:
  create_release_pr:
    name: Create the Release pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Read the current version
        id: version
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "version.properties"
          properties: "templateScriptVersion"

      - uses: nimblehq/github-actions-workflows/create_release_pr@0.1.5
        with:
          token: ${{ github.token }}
          version: ${{ steps.version.outputs.templateScriptVersion }}
          base_branch: main-0.6
          changelogConfiguration: ".github/workflows/changelog-config.json"
          assignee: luongvo-bot
