name: Create the Release pull request

on:
  workflow_dispatch:
  # testing
  push:
    branches:
      - feature/create-release-pr-workflow

jobs:
  create_release_pr:
    name: Create the Release pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read the current version
        id: version
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "version.properties"
          properties: "templateScriptVersion"

      - name: Find HEAD commit
        id: head
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/workflows/changelog-config.json"
          # Listing PRs from the last tag to the HEAD commit
          toTag: ${{ steps.head.outputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create the Release pull request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     assignees: ${{ secrets.GITHUB_USER }}
      #     token: ${{ github.token }}
      #     commit-message: '[Chore] Create the Release pull request'
      #     committer: Nimble Bot <bot@nimblehq.co>
      #     branch: release/${{ steps.version.outputs.templateScriptVersion }}
      #     base: develop
      #     delete-branch: true
      #     title: 'Release - ${{ steps.version.outputs.templateScriptVersion }}'
      #     labels: |
      #       type : release
      #     body: |
      #       https://github.com/nimblehq/android-templates/milestone/TODO

      #       ${{ steps.changelog.outputs.changelog }}

      - name: Create the Release pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base main-0.6 \
            --head release/${{ steps.version.outputs.templateScriptVersion }} \
            --title 'Release - ${{ steps.version.outputs.templateScriptVersion }}' \
            --body 'https://github.com/nimblehq/android-templates/milestone/TODO

            ${{ steps.changelog.outputs.changelog }}' \
